### ISSUE TITLE
Go Mod: v2 tag

### ISSUE THREAD

**Issue by TheMarstonConnell** [wealdtech/go-merkletree#7]
Current if I try to import the newest release (v2.5.0), the module version doesn't match the tag's major version number. Either the projects package name needs to be changed from `github.com/wealdtech/go-merkletree` to `github.com/wealdtech/go-merkletree/v2` or the entire project needs to be cloned into a `v2` folder inside the project for some backwards compatibility. I'm in favour of the first option as github does a pretty good job of managing old tags.

**Comment by mcdee** [comment]
Addressed in #8
